---
title: "Introduction"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

```{r setup, include=FALSE,echo=FALSE,message = FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE, fig.align="center")
library(tidyverse)
library(fontawesome)
library(kableExtra)
# devtools::install_github("hadley/emo")
library(emoji)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

<!-- https://stackoverflow.com/questions/48506712/kable-kableextra-cells-with-hyperlinks  -->
<!-- <link rel="stylesheet" href="styles.css" type="text/css"> -->
<!-- <link rel="stylesheet" href="academicons.min.css"/> -->
<!-- Webpage tutorial: http://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html  -->

This list began as part of the group project for the 2011 edition of my graduate course in Plant-Animal Interactions. As part of the class, my students developed a guide to the native tree species of the University of Florida campus, with information on the their dispersers, pollinators, and herbivores. The students also wrote a [paper in the _Bulletin of the Ecological Society of America_](https://www.jstor.org/stable/bullecosociamer.93.4.390) describing the process and laying out some of the ways smartphones can be used in ecological research, teaching, and extension).

## Essential Accessories 

1. **A lanyard: **minimizes the risk of your phone getting damaged should it slip out of your hands or fall out of your pocket or pack. It is also a much quicker way to alternate between the phone and work requiring two hands.  You can find loads of wrist and neck lanyards online; including [glow-in-the-dark ones](http://www.usalanyards.com/glow-in-the-dark-cell-phone-straps-ly-603.aspx) that seem like they would be good for people working at night).

    Many lanyards require cases or phones with a lanyard slot. If your phone or case doesn't have one (e.g., iPhones), you can you can buy an aftermarket clip that you screw into the baseplate of your phone and just attach the lanyard to that. Right now I am using a carabiner clip from Poddities, which I just clip to the inexpensive but very sturdy UCSD Revelle College lanyard I use to carry my keys, though note it may not work with all cases and charging stands. If this is too big for your taste Poddities also makes a very low-profile base clip called the Netsuke (buy on Amazon), but note when my lanyard got snagged on a branch it slightly bent the base plate, making it a bit tough to for the Lightning cable to fit  properly.  

    Beeline has launched a sweet-looking case with a built in retractable carabiner clip. UPDATE: My new fav is this simple, inexpensive silicone cell phone sling that you can clip to a lanyard.  

2. **A drop-resistant case: **lots of blog posts summarize the options (e.g., ---, ----, ---). If you run the risk of dropping your pack in a stream or you work in environments where it rains, consider a case or sleeve that is waterproof but still allows you to use your phone for data entry.

3. **Other Accessories**

     - **Microphone.** Essential if you record audio or conduct interviews. If you do playback you probably want better speakers too - the speakers on this list are all waterproof.

      - **Selfie Stick.** I know, I know.  But it is useful for pictures of plots you can't reach, branches, and yes pictures of you doing field work. And don't pretend you didn't want an excuse to buy one. Get one with bluetooth shutter.
      
      - **Monopod or Tipod.**

      - **Photo Lens Kit**  Do you take photos in the field? Insects or leaves with a macro lens? Canopy photos with a fisheye lens? There are plenty of reviews of lens kits out there (maybe we can convince Alex to post an update to this 2010 Myrmecos.net post?).

      - Where to buy accessories: In addition to Amazon, check out Photojojo, which has has a million (mostly iphone) accessories aimed at photographers, and there is  a lot here that would be of use to field scientists.


## Apps (by Category)

### Field Safety & Communications  

1. [SOS One Click](https://appadvice.com/app/sos-one-click-send-emergency-alert-help-messages-through/625607281): send gps-referenced messages when you need help via text, email, posts to social media profiles 
1. [Compass](http://hrtapps.com/) `r fa("apple", fill="gray")`
1. [50 apps that could save your life in an emergency](http://prepared-housewives.com/emergency-apps-that-might-just-save-your-life/): Includes first aid, disaster preparedness, emergency alerts, and more.  

### Recording Data, Creating Forms

1. [EpiCollect](https://five.epicollect.net/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
1. [KoBoToolbox](https://www.kobotoolbox.org/)  `r fa("android", fill = "gray")`
1. [iFormBuilder](https://www.zerionsoftware.com/iformbuilder)  `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
1. [Ushahidi](https://www.ushahidi.com/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`: geared towards crowd-sourced data, allows SMS submissions  
1. [Map of Life](https://mol.org/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
1. [CyberTracker](https://cybertracker.org/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")` 
1. [PhenomApp](https://knowledge-base.phenome-networks.com/kb/en/article/phenomapp) `r fa("android", fill = "gray")`: record observations and selections on plants and plots in the field 
1. [Sightings](https://apps.apple.com/au/app/sightings/id539447284) `r fa("apple", fill="gray")`
1. [Neukadye](https://www.neukadye.com/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`:  Time-stamped and geo-located field Notes
1. [CitSci.org](CitSci.org) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`: designed for developing Citizen Science projects/data collection apps but looks to have utility far beyond that.
1. [Germinate Scan](https://ics.hutton.ac.uk/germinate-scan/) `r fa("android", fill = "gray")`: barcode scanning & data recording |
1. Paid platforms for building forms and remote data collection; hard to imagine a project that would require these instead of one of the free options above: [Pendragon Forms](https://www.pendragonforms.com/), [Easy Data](https://www.easydata.nl/), [AmigoCloud](https://amigocloud.com/), [Open Data Kit](https://getodk.org/), [Fulcrum](https://www.fulcrumapp.com/)

### Leaf Area, Canopy Cover, Herbivory, & Plant Traits

1. Canopy Cover and LAI
      * [Canopeo](https://www.canopeoapp.com/#/login) `r fa("android", fill = "gray")`
      * [Canopy Capture](https://nikp29.github.io/CanopyCapture/) `r fa("android", fill = "gray")`
      * [Gap Light Aalysis](https://play.google.com/store/apps/details?id=new4.glama.glamanew4&hl=en_US&gl=US)  `r fa("android", fill = "gray")`
      * [Pocket LAI](https://cassandratech.it/en/pocketlai-en/) (see also [this link](http://www.cassandralab.com/mobiles/1)) `r fa("android", fill = "gray")` `r fa("dollar-sign", fill = "gray")` _(highly discounted for education)_
1. Leaf Area
      * [Easy Leaf Area](https://play.google.com/store/apps/details?id=com.heaslon.EasyLeafArea&hl=en_US&gl=US) `r fa("android", fill = "gray")`
      * [LeafScan](http://www.leafscanapp.com/) `r fa("android", fill = "gray")`
      * [Petiole](https://petioleapp.com/leaf-area-measurement-petiole/) `r fa("android", fill = "gray")`
      * [Leaf-IT](https://play.google.com/store/apps/details?id=de.yahoo.gisopillar.leafit&hl=en_US&gl=US) `r fa("android", fill = "gray")`
1. Herbivory
      * [LeafByte](https://zoegp.science/leafbyte) `r fa("apple", fill = "gray")`
1. Leaf Nitrogen
    * [PocketN](http://www.cassandralab.com/mobiles/3): estimation of nitrogen content in plant tissues.
1. DBH (with LiDAR) and [3D Scanner App](https://3dscannerapp.com/) `r fa("apple", fill = "gray")`. See [this example](https://sketchfab.com/3d-models/ipad-pro-lidar-forest-plot-scanning-fd6fed3a19d14f50ba4801b6c1a6ed60) and [paper by Martin Mokroš et al.](https://www.sciencedirect.com/science/article/pii/S0303243421002191)
    
### Information on Local Environments

1. [SoilWeb](https://casoilresource.lawr.ucdavis.edu/gmap/): portable version of online interface to USDA-NRCS digital soil survey   
1. Solar/Lunar Position, Timing, Duration, & Tracking
    * [Sun position and path](https://apps.apple.com/us/app/sun-position-and-path/id1502500167) `r fa("apple", fill = "gray")`
    * [LightTrac](https://apps.apple.com/us/app/lighttrac/id392892355) `r fa("apple", fill = "gray")` `r fa("dollar-sign", fill = "gray")`
    * [Sun Surveyor Lite](https://apps.apple.com/us/app/sun-surveyor-lite/id552754407) `r fa("apple", fill = "gray")`
1. [RiverFlows](https://play.google.com/store/apps/details?id=com.riverflows&hl=en_US&gl=US) `r fa("apple", fill = "gray")`
1. [WaterTracker](https://data.pointblue.org/apps/autowater/): view data from USGS and NOAA gauge sites to get real-time river-level information.  
1. [Marine Weather Plus](https://www.androidweather.net/download-marine-weather-plus.html) `r fa("android", fill = "gray")` `r fa("dollar-sign", fill = "gray")`: marine forecasts, live buoy data, tides, radar, & sea surface temperatures
1. [DarkSkyMeter](https://apps.apple.com/us/app/dark-sky-meter/id602989060) `r fa("apple", fill = "gray")` `r fa("dollar-sign", fill = "gray")`: Estimate the brightness of the night sky with phone camera

### Timers, Measurement, Counting, Sampling

1. [PocketVJ](http://www.cassandralab.com/mobiles/2): optimal sample size determination
1. Random Number Generators (many more options)
    * [Randomize](https://play.google.com/store/apps/details?id=com.giannis.randomizer&hl=en_US&gl=US) `r fa("android", fill = "gray")`
    * [RNG Plus](https://play.google.com/store/apps/details?id=com.randomappsinc.randomnumbergeneratorplus&hl=en_US&gl=US) `r fa("android", fill = "gray")`
    * [Number Generator](https://apps.apple.com/us/app/random-all-things-generator/id1128190780) `r fa("apple", fill = "gray")`
    * [Random](https://apps.apple.com/us/app/pretty-random-rng/id1126199480) `r fa("apple", fill = "gray")`
1. Rangefinders & Tape measures (many options)
    * [Smart Measure](https://play.google.com/store/apps/details?id=kr.sira.measure)`r fa("android", fill = "gray")`
    * [Moasure - smart tape measure](https://apps.apple.com/us/app/moasure-smart-tape-measure/id1119132775) `r fa("apple", fill = "gray")`
1. [Theodolite](http://hrtapps.com/): overlays real time information about position, altitude, bearing, range, and inclination on the live camera image `r fa("apple", fill = "gray")` 
1. [Converter+](https://apps.apple.com/us/app/converter-units-currencies/id370146222): conversion of units. 100s of units (weight, distance, you name it). `r fa("apple", fill = "gray")` 
1. [Tally Counters](https://thomastsopanakis.com/tally-counters/) by Thomas Tsopanakis: a clean, simple, customizable counter `r fa("apple", fill = "gray")` 
[Tall Counter](https://play.google.com/store/apps/details?id=de.cliff.strichliste&hl=en_US&gl=US) `r fa("android", fill = "gray")`
1. [Tally Counter Pro](http://pixelresearchlabs.com/tallycounter) by Pixel Research Labs. `r fa("apple", fill = "gray")`     
1. [Neukadye Timestamped Field Data](https://www.neukadye.com/mobile-applications/timestamped-field-notes/) (counters, timers, note for species time budget recording)  `r fa("apple", fill = "gray")` `r fa("android", fill = "gray")`

### Field Guides

##### Multi-Taxa
1. [iNaturalist](https://www.inaturalist.org/) `r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`
1. [Map of Life](https://mol.org/mobile#/0/4) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`

##### Plants
1. [Plant-o-Matic](https://apps.apple.com/us/app/plant-o-matic/id906932765)  `r fa("apple", fill="gray")`: The BIEN Plant-O-Matic generates a list of plant species at 100 sq. km resolution for any location in the Americas. Pictures and information help you identify and learn about each species. See the [paper about it](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.12548) in _Methods in Ecology & Evolution_.
1. [National Wildlife Federation](https://www.nwf.org/natureguides) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
1. [vTree](https://dendro.cnre.vt.edu/dendrology/vtree.htm) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
1. [Leafsnap](http://leafsnap.com/) `r fa("apple", fill="gray")` 
<!-- 1. [Guide to Trees of U Florida Campus]() -->
1. [The OSU Campus Tree and Plant App](https://chadwickarboretum.osu.edu/research-and-education/campus-tree-mapping-0)
<!-- 1. [NY Flora Association Blog](): A list of field guides for iPhone/iPad has been put together by the NY Flora Association and can be found here. It includes guides to everything from plants to mushrooms. -->

##### Birds
1. [iBird](https://ibird.com/)`r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
1. [Larkwire](https://www.larkwire.com/) `r fa("apple", fill="gray")`: game-based system for learning bird songs
1. [Audubon Bird Guide](https://www.audubon.org/app) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
<!-- 1. [National Geographic Bird guide]() -->
1. [Sibley eGuide to Birds v2](https://www.sibleyguides.com/product/sibley-birds-v2-app/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
1. [Merlin](https://merlin.allaboutbirds.org/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
1.  [National Wildlife Federation](https://www.nwf.org/natureguides) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`

##### Fish  
1. [Guides to Fish of the East Pacific](https://apps.apple.com/us/app/fishes-east-pacific/id494644648) by Ross Robertson `r fa("apple", fill="gray")`
1. [Guides to Fish of the Caribbean](https://apps.apple.com/us/app/fishes-greater-caribbean/id570048678) by Ross Robertson `r fa("apple", fill="gray")`
  
##### Reptiles and Amphibians
1. [National Wildlife Federation](https://www.nwf.org/natureguides) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`

##### Insects & Spiders
1. [National Wildlife Federation](https://www.nwf.org/natureguides) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
1. [Kaeferkunde](http://kaeferkunde.de/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`: interactive guide to beetles in German

##### Fungi
1. [Shroomify](https://foragers-friend.com/download-app.php) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
1. [National Wildlife Federation](https://www.nwf.org/natureguides) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`

##### Mammals 
1. [Guide to wildlife of UCSC Campus](https://play.google.com/store/apps/details?id=reserve.natural.wildlifeiducsc&hl=en_US&gl=US) `r fa("android", fill = "gray")`
1. [National Wildlife Federation](https://www.nwf.org/natureguides) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`

##### Animal Tracks
1. [iTrack Wildlife](http://www.naturetracking.com/itrack-wildlife/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`


### Mapping, GIS, & GPS

1. [GPS Essentials](https://play.google.com/store/apps/details?id=com.mictale.gpsessentials&hl=en_US&gl=US) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
1. [iGIS](https://www.geometry.com.au/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
<!-- 1. [ArcGIS AppStudio](https://www.esri.com/en-us/arcgis/products/arcgis-appstudio/overview)   -->
1. [Google Maps](https://support.google.com/maps/answer/6139433?hl=en#zippy=) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")` 
1. [Google Earth](https://www.google.com/earth/versions/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
<!-- 1. [gvSIG mini]()   -->
1. [GPS Status & Toolbox](https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2&hl=en_US&gl=US) `r fa("android", fill = "gray")`
1. [OsmAnd: Offline Mobile Apps and Navigation](https://osmand.net/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`
1. [LocusPro](https://www.locusmap.app/?gclid=Cj0KCQiA3-yQBhD3ARIsAHuHT665byc1nhe4Eb6_H1ack2JvkW-5DQKVTacj_CDgIO-QfUOePPYRmnYaAoaNEALw_wcB) `r fa("android", fill = "gray")`
1. [HERE WeGo](https://wego.here.com/?x=ep&map=29.6825,-82.3606,10,normal) `r fa("android", fill = "gray")` `r fa("apple", fill="gray")` independent of a data signal (maps preload) and provides voice navigation, tilt and night views, 3D cities, and numerous gps-enhanced services
1. [AllTrails](https://www.alltrails.com/): record trip route, add photos and videos, share route, and download to google earth `r fa("android", fill = "gray")` `r fa("apple", fill="gray")`
<!-- 1. [PhenoMap](): map plantphenology; upload images to a Flickr group.   -->
1. [WolfGIS](https://download.cnet.com/Wolf-GIS-APEX/3000-12940_4-75457099.html) `r fa("apple", fill="gray")`
<!-- 1. [GISRoam]()  -->
1. [MapIt GIS](https://mapitgis.com/) `r fa("android", fill = "gray")`
1. [Cartographica Mobile](https://www.macgis.com/mobile) `r fa("android", fill = "gray")` `r fa("apple", fill="gray")`
1. [QGIS](https://www.qgis.org/en/site/) `r fa("android", fill = "gray")`
1. [GPS Kit](https://apps.apple.com/us/app/gps-kit-offline-gps-tracker/id287909017) `r fa("android", fill = "gray")` 
1. [UTM RD GPS coords converter](https://apps.apple.com/us/app/utm-rd-gps-coords-converter/id1440292872). Convert degrees to UTM and _vice versa_.  `r fa("android", fill = "gray")`
1. [MeasureMap](https://apps.apple.com/us/app/measure-map/id1247360674): lets you draw polygons on a hybrid Google map, save the polygons, and export as KML, CSV, PNG, MMP (proprietary format), and PDF. 
<!-- (h/t EarthKnight who has a nice post describing apps used in his fieldwork)   -->
1. [OruxMaps](https://www.oruxmaps.com/cs/en/):Especially useful for offline maps. `r fa("android", fill = "gray")`  
 
### Participatory Science

##### Herps
1. [HerpMapper](https://www.herpmapper.org/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`  

##### Birds
1. [African Raptor Observations](https://www.androidblip.com/android-apps/com.fluidfacades.habitatinfo.rapterobs.html): accurately locate raptor sightings even while offline and send in from anywhere on the continent.  Perhaps under Data Entry and Recording Observations  
* [BirdLog](https://ebird.org/caribbean/news/birdlog) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")` `r fa("dollar-sign", fill = "gray")` the official app for data entry into the Cornell Lab of Ornithology's bird project.  

##### Plants  
1. [Project Budburst](https://budburst.org/the-app) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`: national field campaign designed to engage the public in the collection of data on timing of leafing, flowering, and fruiting of plants  
1. [CalFlora](https://www.calflora.org/) `r fa("apple", fill="gray")` `r fa("android", fill = "gray")`: report native plant occurrences in California and then visualize them on the CalFlora map.
  
##### Invasive Species
1. [What’s Invasive!](https://www.eddmaps.org/): submit geotagged photos and observations of invasive species
1. [IveGot1](https://myfwc.com/wildlifehabitats/nonnatives/report/) `r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`: Identify and report Invasive Species in Florida    
1. [iMapInvasives]([iMapInvasives](https://www.imapinvasives.org/) `r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`

##### Multi-Taxa
1. [iNaturalist](https://www.inaturalist.org/) `r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`
1. [Project Noah](https://www.projectnoah.org/)`r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`
1. [Nature's Notebook Android App](https://play.google.com/store/apps/details?id=org.usanpn.naturesnotebookmobile&hl=en_US&gl=US): from USA-NPN's. Record observations on hundreds of species of plants and animals, as well as add new locations and species to your list in the field.  `r fa("android", fill = "gray")`

##### Environmemntal Conditions
1. [Loss of the Night](http://lossofthenight.blogspot.com/2015/01/brief-introduction-to-loss-of-night-app.html) `r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`: for estimating the brightness of the night sky as part of a project on light pollution
1. [Secchi](http://www.secchidisk.org/) `r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`: the Secchi Disk project encourages participation in a global study of phytoplankton in the sea by creating and using their own secchi disk.
1. [mPing](https://mping.nssl.noaa.gov/): report on precipitation
1. [Marine Debris Tracker](https://debristracker.org/): log trash on coastlines and waterways
1. [NoiseTube](http://www.noisetube.net/): monitor noise pollution with your smartphone
<!-- 1. [Creekwatch](): monitor the quality of your local watershed   -->

##### Roadkill
1. [Urubu Mobile](https://sistemaurubu.com.br/)  `r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`: Developed by Brazil's Federal University in Lavras' Center for The Study of Road Ecology (UFLA/CBEE) this cool app is used to register animal roadkill to study and mitigate the impacts of roads (read more here and here). Available for download for Android phones here.  PS "Urubu" is "vulture"in Portuguese...typical Brazilian sense of humor!  

##### Widlife Trafficking
1. [Wildlife Witness](https://www.wildlifewitness.net/) `r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`: allows tourists & locals to easily report wildlife trade by taking a photo, pinning the exact location of an incident and sending these important details to the wildlife trade monitoring netw[ork TRAFFIC (NB: this is AWESOME)  

### Workflow & Data Upload / Storage

1. [Dropbox](https://www.dropbox.com/) `r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`
1. [Evernote](https://evernote.com/) `r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`
1. [Google Drive, Sheets, & Docs](https://www.google.com/) `r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`
1. [IFTTT](https://ifttt.com/) `r fa("apple", fill="gray")`, `r fa("android", fill = "gray")`
<!-- 1. NB: [Google Forms](https://www.google.com/forms/about/) isn't listed because it isn't really suited to  -->
<!-- ## Tools for programming your own app -->

## Other Lists, Researchers

1. Check Out Dr. Jere Boudell's [Mobile Computing in the Sciences](https://jabmobilecomp.mystrikingly.com/) Page, which includes information on App EcoHackathons at ESA and other meetings.
1. [Green Apps & Web](https://www.greenappsandweb.com/): app creator with a number of different apps en Español.


## Contributions & Corrections

If you would like to recommend an app for the list or suggest an edit, please do so as a 'new issue' [here](https://github.com/BrunaLab/apps_for_fieldwork/issues) or as a [pull request](https://github.com/BrunaLab/apps_for_fieldwork/pulls).


## References

1. Boudell, J.A. and B.A. Middleton. 2019. Plot Locator: An app for locating plots in the field. Applications in Plant Sciences 7: e11311. https://doi.org/10.1002/aps3.11311 

1. Teacher, A. G., D. J. Griffiths, D. J. Hodgson, & R. Inger. 2013. Smartphones in ecology and evolution: a guide for the app-rehensive. Ecology and Evolution, 3(16), 5268–5278. https://doi.org/10.1002/ece3.888 

1. Palumbo, M. J., S. A. Johnson, F. M. Mundim, A. C. Wolf, S. Arunachalam, O. Gonzalez, A. Lau, J. L. Ulrich, A. Washuta, E. M. Bruna. 2012. Harnessing smartphones for ecological education, research, and outreach. Bulletin of the Ecological Society of America 93(4):390-393  https://doi.org/10.1890/0012-9623-93.4.390 

